"""add_user_is_admin

Promotable admins. Deliberately NO backfill: the owner account is admin
via config fallback in services.auth.get_current_admin (UPLOAD_OWNER_EMAIL),
never via this flag, so a fresh or upgraded instance needs no data setup.

Revision ID: e0dad03a2233
Revises: 3fc43e0c2d38
Create Date: 2026-06-09 15:29:25.050769
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0dad03a2233'
down_revision: Union[str, None] = '3fc43e0c2d38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
