"""add_deck_moderation_and_events

Revision ID: 1d6992afeaad
Revises: 01cc22f061ee
Create Date: 2026-06-09 13:36:41.741596
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d6992afeaad'
down_revision: Union[str, None] = '01cc22f061ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=12), nullable=False),
    sa.Column('reasons', sa.Text(), nullable=False),
    sa.Column('deck_title', sa.String(length=300), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('owner_email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_events_action'), 'moderation_events', ['action'], unique=False)
    op.create_index(op.f('ix_moderation_events_created_at'), 'moderation_events', ['created_at'], unique=False)
    op.add_column('decks', sa.Column('moderation_status', sa.String(length=12), server_default='approved', nullable=False))
    op.add_column('decks', sa.Column('moderation_reasons', sa.Text(), nullable=True))
    op.add_column('decks', sa.Column('flagged_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_decks_moderation_status'), 'decks', ['moderation_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decks_moderation_status'), table_name='decks')
    op.drop_column('decks', 'flagged_at')
    op.drop_column('decks', 'moderation_reasons')
    op.drop_column('decks', 'moderation_status')
    op.drop_index(op.f('ix_moderation_events_created_at'), table_name='moderation_events')
    op.drop_index(op.f('ix_moderation_events_action'), table_name='moderation_events')
    op.drop_table('moderation_events')
    # ### end Alembic commands ###
