"""add_deck_search_text

Revision ID: 4ba74185d6ac
Revises: 402ac445cb16
Create Date: 2026-06-09 18:11:44.947675
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ba74185d6ac'
down_revision: Union[str, None] = '402ac445cb16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('search_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decks', 'search_text')
    # ### end Alembic commands ###
