"""add_deck_visibility

Revision ID: 01cc22f061ee
Revises: 1d66dca4c214
Create Date: 2026-06-07 01:02:34.258260
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01cc22f061ee'
down_revision: Union[str, None] = '1d66dca4c214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('visibility', sa.String(length=12), server_default='public', nullable=False))
    op.create_index(op.f('ix_decks_visibility'), 'decks', ['visibility'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decks_visibility'), table_name='decks')
    op.drop_column('decks', 'visibility')
    # ### end Alembic commands ###
